server:
  port:8080
  
eureka: 
   client: 
      serviceUrl: 
         defaultZone: http://localhost:8090/eureka  
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: catalog-service
        uri: lb://catalog-SERVICE
        predicates:
        - Path=/catalog/**
      - id: order-service
        uri: lb://order-SERVICE
        predicates:
        - Path=/order/**  

